### ISSUE TITLE
2FA code displays in e107_admin/users.php?mode=main&action=list as UEF

### ISSUE THREAD

**Issue by Moc** [e107inc/twofactorauth#5]
@CaMer0n How can I prevent the 2FA UEF showing up as a column to select? 

![image](https://user-images.githubusercontent.com/577978/131396251-307cda56-fbf0-417a-9fa8-6a342bd5b7a1.png)

It's using the e_user.php addon.

**Comment by CaMer0n** [comment]
Did you try adding "nolist" => true to the field?

**Comment by Moc** [comment]
@CaMer0n In e_user.php? Just tried it, but doesn't work. The field still displays in the selection. 

```
$fields['secret_key'] = array(
			'title' 	=> LAN_PLUGIN_2FA_NAME_FULL,  
			'read'		=> e_UC_NOBODY, 
			'write'		=> e_UC_MEMBER,
			'fieldType' => 'varchar(255)',       
			'type' 		=> 'method', 
			'data'		=> 'str', 
			'required'	=> false,
			'nolist'	=> true,
		); 
```

I uninstalled the plugin, cleared caches, re-installed. No change.

**Comment by CaMer0n** [comment]
Does this fix it?

```
function settings()
	{
		$fields = array();
		$fields['secret_key'] = array(
			'title' 	=> '_system_',
			'read'		=> e_UC_NOBODY, 
			'write'		=> e_UC_MEMBER,
			'fieldType' => 'varchar(255)',       
			'type' 		=> 'method', 
			'data'		=> 'str', 
			'required'	=> false,
		); 

        return $fields;

	}

```
