### ISSUE TITLE
Backup code

### ISSUE THREAD

**Issue by parsfounder** [e107inc/twofactorauth#6]
Recovery code is missing! is that ok to use this plugin on a live website?

**Comment by Moc** [comment]
Correct, the library that this plugin uses (https://github.com/RobThree/TwoFactorAuth) does not support recovery codes. Such functionality will thus not be implemented. 

An administrator can always disable 2FA on any user account. Ultimately, if regular access to the Admin Area is not possible, the website administrator can also directly access the database in case of emergency to disable 2FA for specific users. I'll post instructions on how to do so in the documentation. 

Keeping the issue open until documentation has been added.

**Comment by Moc** [comment]
I decided to implement a recovery code functionality anyway. Will be included in the next release (2.0.0). 

Leaving this issue open until the flood protection element is added as well.

**Comment by Moc** [comment]
This is now completed. Should all be working but let me know if there's any issues.
